
package trng.imcs.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "MobileService", targetNamespace = "http://www.imcs.trng/MobileService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MobileService {


    /**
     * 
     * @param request
     * @return
     *     returns trng.imcs.soap.RechargeMobileResponse
     */
    @WebMethod(action = "http://www.imcs.trng/MobileService/rechargeMobile")
    @WebResult(name = "RechargeMobileResponse", targetNamespace = "http://www.imcs.trng/RechargeMobile", partName = "response")
    public RechargeMobileResponse rechargeMobile(
        @WebParam(name = "RechargeMobileRequest", targetNamespace = "http://www.imcs.trng/RechargeMobile", partName = "request")
        RechargeMobileRequest request);

}
